version: '3'

networks:
  chat:
    driver: bridge

services:

  nginx:
    container_name: chat-nginx
    image: nginx:1.23.1
    restart: always
    depends_on:
      - "php"
    volumes:
      - ../server:/chat/server
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./log/nginx/logs:/logs
    networks:
      - chat
    ports:
      - "80:80"




  php:
    container_name: chat-php
    image: likeshop/php:8.0.22-fpm
    restart: always
    working_dir: /chat/server
    volumes:
      - ../server:/chat/server
      - ./config/php/ini/docker-php80-ext-swoole-compiler.ini:/usr/local/etc/php/conf.d/docker-php80-ext-swoole-compiler.ini
      - ./config/php/so/swoole_loader80.so:/usr/local/lib/php/extensions/no-debug-non-zts-20200930/swoole_loader80.so
    networks:
      - chat
    ports:
      - "9000:9000"
    #user: "1001:1001" #//linux环境启用，主机当前运行用户id:当前运行用户组id，可以使用"id 用户名"命令获取，宝塔一般直接使用即可


  mysql:
    container_name: chat-mysql
    image: mysql:5.7.29 #X86架构
    #image: amd64/mysql:5.7.29 #arm架构M1、M2x芯片专用
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/mysql5.7.29/lib:/var/lib/mysql
      - ./config/mysql/mysqld.cnf:/etc/mysql/my.cnf
    networks:
      - chat
    ports:
      - "3306:3306"


  redis:
    container_name: chat-redis
    image: redis:7.0.4
    restart: always
    volumes:
      - ./data/redis:/data
    networks:
      - chat
    ports:
      - "6379:6379"